name: CI - Build and Deploy to ECS

on:
  push:
    branches: [develop]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -out=tfplan \
          -var="frontend_image=${{ secrets.ECR_FRONTEND_REPO }}:${{ env.IMAGE_TAG }}" \
          -var="backend_image=${{ secrets.ECR_BACKEND_REPO }}:${{ env.IMAGE_TAG }}"

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve tfplan
